### PR TITLE
Lots of things...

### PR DESCRIPTION
**Pull request by kbiesiadecki141**
Mostly these consist of mecanum wheel adaptations and beacon autonomous work.

### CODE REVIEW

**Comment by cmacfarl** [comment]
You are still working in FTC-Team-25/java/team25core?

I migrated you, and everything you had outstanding, to terkel a couple of
weeks ago.  What's going on here?

**Comment by cmacfarl** [comment]
Or were those commits prior to the migration, and are therefore just
duplicates?  I just want to make sure that all the software you will be
using for competition is where it should be so that there are no surprises.

**Comment by kbiesiadecki141** [comment]
The changes occurred prior to migration. Right now, Elizabeth and I are both using terkel.

**Comment by cmacfarl** [comment]
Ack.  Thanks.

**Pull request merged**
